# Generated by Django 3.1.7 on 2021-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=200)),
                ('owner_phone_number', models.CharField(max_length=200)),
                ('restaurant_address', models.CharField(max_length=200)),
            ],
        ),
    ]
