# Generated by Django 3.1.7 on 2021-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_restaurantdetails_mentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=200)),
                ('owner_phone_number', models.CharField(max_length=200)),
                ('restaurant_address', models.CharField(max_length=200)),
                ('mentions', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='RestaurantDetails',
        ),
    ]
