# Generated by Django 3.1.7 on 2021-05-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestaurantApp', '0014_auto_20210517_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant')),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.tableid')),
            ],
        ),
    ]
