# Generated by Django 3.1.7 on 2021-05-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0014_auto_20210517_0959'),
        ('OrdersApp', '0002_remove_ordermodel_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.tableid'),
            preserve_default=False,
        ),
    ]
