# Generated by Django 3.1.7 on 2021-05-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0004_fooditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.ordermodel'),
            preserve_default=False,
        ),
    ]
