# Generated by Django 3.1.7 on 2021-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0005_fooditems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='requested_payment',
            field=models.BooleanField(default=False),
        ),
    ]
