# Generated by Django 3.1.7 on 2021-06-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestaurantApp', '0014_auto_20210517_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_first_name', models.CharField(max_length=30)),
                ('staff_last_name', models.CharField(max_length=30)),
                ('staff_position', models.CharField(max_length=50)),
                ('employment_date', models.DateField(default='')),
                ('staff_phone', models.CharField(default='', max_length=20)),
                ('staff_email', models.EmailField(default='', max_length=254)),
                ('staff_gender', models.CharField(choices=[('F', 'Feminine'), ('M', 'Masculine')], max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant')),
            ],
        ),
    ]
