# Generated by Django 3.1.7 on 2021-04-06 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0004_auto_20210406_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='food_categ',
            new_name='food_category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant'),
        ),
    ]
