# Generated by Django 3.1.7 on 2021-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0009_auto_20210406_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableid',
            name='table_unique_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ManyToManyField(blank=True, to='RestaurantApp.Restaurant'),
        ),
    ]
