# Generated by Django 3.1.7 on 2021-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0010_auto_20210407_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredient',
            name='ingredient_quantity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
