# Generated by Django 3.1.7 on 2021-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0011_foodingredient_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingredient',
            name='ingredient_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
