# Generated by Django 3.1.7 on 2021-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0012_auto_20210407_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.TextField(default=''),
        ),
    ]
